// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(31,27,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(15,150,2^(33.917802))
// 
// Ring
// degree d = 64
// modulus q = 281474976710909, log(q) ~ 48.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 423812, log(gamma) ~ 18.693065
// 
// Dimensions of secrets
// s1: m1 = 92
// m: l = 0
// s2: m2 = 58
// 
// Size of secrets
// l2(s1) <= alpha = 77.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 88)
// exact euclidean: yes (dimensions: [4], bounds: [16.0])
// approximate infinity: yes (psi: 2335.2631, dimension: 24, bound: 2944.4996)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 101580.8, log(stdev1/1.55) = 16.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 203161.6, log(stdev4/1.55) = 17.0
// 
// Repetition rate
// M1 = 4.1890974
// M2 = 2.465778
// M3 = 1.0251938
// M4 = 1.0360287
// total = 10.97115
// 
// Security
// MSIS dimension: 15
// MSIS root hermite factor: 1.0043356
// MLWE dimension: 31
// MLWE root hermite factor: 1.0042818
// 
// Proof size
// ~ 31.2949218750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _las_pi_params_q_limbs[] = {281474976710909UL};
static const int_t _las_pi_params_q = {{(limb_t *)_las_pi_params_q_limbs, 1, 0}};
static const limb_t _las_pi_params_qminus1_limbs[] = {281474976710908UL};
static const int_t _las_pi_params_qminus1 = {{(limb_t *)_las_pi_params_qminus1_limbs, 1, 0}};
static const limb_t _las_pi_params_m_limbs[] = {664150559UL};
static const int_t _las_pi_params_m = {{(limb_t *)_las_pi_params_m_limbs, 1, 0}};
static const limb_t _las_pi_params_mby2_limbs[] = {332075279UL};
static const int_t _las_pi_params_mby2 = {{(limb_t *)_las_pi_params_mby2_limbs, 1, 0}};
static const limb_t _las_pi_params_gamma_limbs[] = {423812UL};
static const int_t _las_pi_params_gamma = {{(limb_t *)_las_pi_params_gamma_limbs, 1, 0}};
static const limb_t _las_pi_params_gammaby2_limbs[] = {211906UL};
static const int_t _las_pi_params_gammaby2 = {{(limb_t *)_las_pi_params_gammaby2_limbs, 1, 0}};
static const limb_t _las_pi_params_pow2D_limbs[] = {1024UL};
static const int_t _las_pi_params_pow2D = {{(limb_t *)_las_pi_params_pow2D_limbs, 1, 0}};
static const limb_t _las_pi_params_pow2Dby2_limbs[] = {512UL};
static const int_t _las_pi_params_pow2Dby2 = {{(limb_t *)_las_pi_params_pow2Dby2_limbs, 1, 0}};
static const limb_t _las_pi_params_Bsq_limbs[] = {87116465869491UL, 0UL};
static const int_t _las_pi_params_Bsq = {{(limb_t *)_las_pi_params_Bsq_limbs, 2, 0}};
static const limb_t _las_pi_params_scM1_limbs[] = {11692784830202827229UL, 3488231105071256856UL, 4UL};
static const int_t _las_pi_params_scM1 = {{(limb_t *)_las_pi_params_scM1_limbs, 3, 0}};
static const limb_t _las_pi_params_scM2_limbs[] = {10189608724252333762UL, 8592086691763836887UL, 2UL};
static const int_t _las_pi_params_scM2 = {{(limb_t *)_las_pi_params_scM2_limbs, 3, 0}};
static const limb_t _las_pi_params_scM3_limbs[] = {8243026857033605067UL, 464743631203460493UL, 1UL};
static const int_t _las_pi_params_scM3 = {{(limb_t *)_las_pi_params_scM3_limbs, 3, 0}};
static const limb_t _las_pi_params_scM4_limbs[] = {13154748848107959420UL, 664611648963551184UL, 1UL};
static const int_t _las_pi_params_scM4 = {{(limb_t *)_las_pi_params_scM4_limbs, 3, 0}};
static const limb_t _las_pi_params_stdev1sq_limbs[] = {10318658929UL, 0UL};
static const int_t _las_pi_params_stdev1sq = {{(limb_t *)_las_pi_params_stdev1sq_limbs, 2, 0}};
static const limb_t _las_pi_params_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _las_pi_params_stdev2sq = {{(limb_t *)_las_pi_params_stdev2sq_limbs, 2, 0}};
static const limb_t _las_pi_params_stdev3sq_limbs[] = {40307261UL, 0UL};
static const int_t _las_pi_params_stdev3sq = {{(limb_t *)_las_pi_params_stdev3sq_limbs, 2, 0}};
static const limb_t _las_pi_params_stdev4sq_limbs[] = {41274635715UL, 0UL};
static const int_t _las_pi_params_stdev4sq = {{(limb_t *)_las_pi_params_stdev4sq_limbs, 2, 0}};
static const limb_t _las_pi_params_inv2_limbs[] = {140737488355454UL};
static const int_t _las_pi_params_inv2 = {{(limb_t *)_las_pi_params_inv2_limbs, 1, 1}};
static const limb_t _las_pi_params_inv4_limbs[] = {70368744177727UL};
static const int_t _las_pi_params_inv4 = {{(limb_t *)_las_pi_params_inv4_limbs, 1, 1}};
static const unsigned int _las_pi_params_n[1] = {4};
static const limb_t _las_pi_params_Bz3sqr_limbs[] = {27753065054UL, 0UL};
static const int_t _las_pi_params_Bz3sqr = {{(limb_t *)_las_pi_params_Bz3sqr_limbs, 2, 0}};
static const limb_t _las_pi_params_Bz4_limbs[] = {3250585UL};
static const int_t _las_pi_params_Bz4 = {{(limb_t *)_las_pi_params_Bz4_limbs, 1, 0}};
static const limb_t _las_pi_params_Pmodq_limbs[] = {62240886891UL};
static const int_t _las_pi_params_Pmodq = {{(limb_t *)_las_pi_params_Pmodq_limbs, 1, 1}};
static const limb_t _las_pi_params_l2Bsq0_limbs[] = {256UL};
static const int_t _las_pi_params_l2Bsq0 = {{(limb_t *)_las_pi_params_l2Bsq0_limbs, 1, 0}};
static const limb_t _las_pi_params_Ppmodq_0_limbs[] = {22205097UL};
static const int_t _las_pi_params_Ppmodq_0 = {{(limb_t *)_las_pi_params_Ppmodq_0_limbs, 1, 0}};
static const limb_t _las_pi_params_Ppmodq_1_limbs[] = {16826409UL};
static const int_t _las_pi_params_Ppmodq_1 = {{(limb_t *)_las_pi_params_Ppmodq_1_limbs, 1, 0}};
static const limb_t _las_pi_params_Ppmodq_2_limbs[] = {10368297UL};
static const int_t _las_pi_params_Ppmodq_2 = {{(limb_t *)_las_pi_params_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _las_pi_params_l2Bsq[] = {_las_pi_params_l2Bsq0};
static const int_srcptr _las_pi_params_Ppmodq[] = {_las_pi_params_Ppmodq_0, _las_pi_params_Ppmodq_1, _las_pi_params_Ppmodq_2};
static const polyring_t _las_pi_params_ring = {{_las_pi_params_q, 64, 49, 6, moduli_d64, 3, _las_pi_params_Pmodq, _las_pi_params_Ppmodq, _las_pi_params_inv2}};
static const dcompress_params_t _las_pi_params_dcomp = {{ _las_pi_params_q, _las_pi_params_qminus1, _las_pi_params_m, _las_pi_params_mby2, _las_pi_params_gamma, _las_pi_params_gammaby2, _las_pi_params_pow2D, _las_pi_params_pow2Dby2, 10, 1, 30 }};
static const abdlop_params_t _las_pi_params_tbox = {{ _las_pi_params_ring, _las_pi_params_dcomp, 93, 58, 0, 12, 15, _las_pi_params_Bsq, 1, 8, 5, 140, 1, 16, _las_pi_params_scM1, _las_pi_params_stdev1sq, 2, 12, _las_pi_params_scM2, _las_pi_params_stdev2sq}};
static const abdlop_params_t _las_pi_params_quad_eval_ = {{ _las_pi_params_ring, _las_pi_params_dcomp, 93, 58, 9, 3, 15, _las_pi_params_Bsq, 1, 8, 5, 140, 1, 16, _las_pi_params_scM1, _las_pi_params_stdev1sq, 2, 12, _las_pi_params_scM2, _las_pi_params_stdev2sq}};
static const abdlop_params_t _las_pi_params_quad_many_ = {{ _las_pi_params_ring, _las_pi_params_dcomp, 93, 58, 11, 1, 15, _las_pi_params_Bsq, 1, 8, 5, 140, 1, 16, _las_pi_params_scM1, _las_pi_params_stdev1sq, 2, 12, _las_pi_params_scM2, _las_pi_params_stdev2sq}};
static const lnp_quad_eval_params_t _las_pi_params_quad_eval = {{ _las_pi_params_quad_eval_, _las_pi_params_quad_many_, 4}};
static const lnp_tbox_params_t _las_pi_params = {{ _las_pi_params_tbox, _las_pi_params_quad_eval, 88, _las_pi_params_n, 24, 1, 93, 2, 12, _las_pi_params_scM3, _las_pi_params_stdev3sq, 2, 17, _las_pi_params_scM4, _las_pi_params_stdev4sq, _las_pi_params_Bz3sqr, _las_pi_params_Bz4, &_las_pi_params_l2Bsq[0], _las_pi_params_inv4, 32046UL }};

static const unsigned int las_pi_params_Ps[88] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87};
static const unsigned int las_pi_params_Es0[4] = {88, 89, 90, 91};
static const unsigned int *las_pi_params_Es[1] = { las_pi_params_Es0, };
static const unsigned int las_pi_params_Es_nrows[1] = {4};

static const limb_t las_pi_params_p_limbs[] = {8380417UL};
static const int_t las_pi_params_p = {{(limb_t *)las_pi_params_p_limbs, 1, 0}};
static const limb_t las_pi_params_pinv_limbs[] = {110484716362069UL};
static const int_t las_pi_params_pinv = {{(limb_t *)las_pi_params_pinv_limbs, 1, 1}};
static const unsigned int las_pi_params_s1_indices[23] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22};
static const lin_params_t las_pi_params = {{ _las_pi_params, 256, las_pi_params_p, las_pi_params_pinv, 4, las_pi_params_s1_indices, 23, NULL, 0,  las_pi_params_Ps, 88, las_pi_params_Es, las_pi_params_Es_nrows, NULL, NULL }};

