// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(32,28,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(16,428,2^(35.956529))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843189, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 12
// gamma = 1887866, log(gamma) ~ 20.848325
// 
// Dimensions of secrets
// s1: m1 = 368
// m: l = 0
// s2: m2 = 60
// 
// Size of secrets
// l2(s1) <= alpha = 151.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 352)
// exact euclidean: yes (dimensions: [16], bounds: [16.0])
// approximate infinity: yes (psi: 2335.5606, dimension: 96, bound: 11776.499)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 812646.4, log(stdev4/1.55) = 19.0
// 
// Repetition rate
// M1 = 4.050698
// M2 = 2.5437218
// M3 = 1.0241657
// M4 = 1.0360193
// total = 10.932956
// 
// Security
// MSIS dimension: 16
// MSIS root hermite factor: 1.0043853
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 78.0625000000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _las_pi_params_k4_q_limbs[] = {1125899906843189UL};
static const int_t _las_pi_params_k4_q = {{(limb_t *)_las_pi_params_k4_q_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_qminus1_limbs[] = {1125899906843188UL};
static const int_t _las_pi_params_k4_qminus1 = {{(limb_t *)_las_pi_params_k4_qminus1_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_m_limbs[] = {596387618UL};
static const int_t _las_pi_params_k4_m = {{(limb_t *)_las_pi_params_k4_m_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_mby2_limbs[] = {298193809UL};
static const int_t _las_pi_params_k4_mby2 = {{(limb_t *)_las_pi_params_k4_mby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_gamma_limbs[] = {1887866UL};
static const int_t _las_pi_params_k4_gamma = {{(limb_t *)_las_pi_params_k4_gamma_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_gammaby2_limbs[] = {943933UL};
static const int_t _las_pi_params_k4_gammaby2 = {{(limb_t *)_las_pi_params_k4_gammaby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_pow2D_limbs[] = {4096UL};
static const int_t _las_pi_params_k4_pow2D = {{(limb_t *)_las_pi_params_k4_pow2D_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_pow2Dby2_limbs[] = {2048UL};
static const int_t _las_pi_params_k4_pow2Dby2 = {{(limb_t *)_las_pi_params_k4_pow2Dby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_Bsq_limbs[] = {1594986090635823UL, 0UL};
static const int_t _las_pi_params_k4_Bsq = {{(limb_t *)_las_pi_params_k4_Bsq_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_scM1_limbs[] = {1159860783202395785UL, 935213586260017012UL, 4UL};
static const int_t _las_pi_params_k4_scM1 = {{(limb_t *)_las_pi_params_k4_scM1_limbs, 3, 0}};
static const limb_t _las_pi_params_k4_scM2_limbs[] = {14597513304372987885UL, 10029897663603524287UL, 2UL};
static const int_t _las_pi_params_k4_scM2 = {{(limb_t *)_las_pi_params_k4_scM2_limbs, 3, 0}};
static const limb_t _las_pi_params_k4_scM3_limbs[] = {13696885788296755127UL, 445779379746186966UL, 1UL};
static const int_t _las_pi_params_k4_scM3 = {{(limb_t *)_las_pi_params_k4_scM3_limbs, 3, 0}};
static const limb_t _las_pi_params_k4_scM4_limbs[] = {10162045565247619750UL, 664439362459985445UL, 1UL};
static const int_t _las_pi_params_k4_scM4 = {{(limb_t *)_las_pi_params_k4_scM4_limbs, 3, 0}};
static const limb_t _las_pi_params_k4_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _las_pi_params_k4_stdev1sq = {{(limb_t *)_las_pi_params_k4_stdev1sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _las_pi_params_k4_stdev2sq = {{(limb_t *)_las_pi_params_k4_stdev2sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_stdev3sq_limbs[] = {161229046UL, 0UL};
static const int_t _las_pi_params_k4_stdev3sq = {{(limb_t *)_las_pi_params_k4_stdev3sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_stdev4sq_limbs[] = {660394171433UL, 0UL};
static const int_t _las_pi_params_k4_stdev4sq = {{(limb_t *)_las_pi_params_k4_stdev4sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_inv2_limbs[] = {562949953421594UL};
static const int_t _las_pi_params_k4_inv2 = {{(limb_t *)_las_pi_params_k4_inv2_limbs, 1, 1}};
static const limb_t _las_pi_params_k4_inv4_limbs[] = {281474976710797UL};
static const int_t _las_pi_params_k4_inv4 = {{(limb_t *)_las_pi_params_k4_inv4_limbs, 1, 1}};
static const unsigned int _las_pi_params_k4_n[1] = {16};
static const limb_t _las_pi_params_k4_Bz3sqr_limbs[] = {111012260217UL, 0UL};
static const int_t _las_pi_params_k4_Bz3sqr = {{(limb_t *)_las_pi_params_k4_Bz3sqr_limbs, 2, 0}};
static const limb_t _las_pi_params_k4_Bz4_limbs[] = {13002342UL};
static const int_t _las_pi_params_k4_Bz4 = {{(limb_t *)_las_pi_params_k4_Bz4_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_Pmodq_limbs[] = {42568471872UL};
static const int_t _las_pi_params_k4_Pmodq = {{(limb_t *)_las_pi_params_k4_Pmodq_limbs, 1, 1}};
static const limb_t _las_pi_params_k4_l2Bsq0_limbs[] = {256UL};
static const int_t _las_pi_params_k4_l2Bsq0 = {{(limb_t *)_las_pi_params_k4_l2Bsq0_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_Ppmodq_0_limbs[] = {18068112UL};
static const int_t _las_pi_params_k4_Ppmodq_0 = {{(limb_t *)_las_pi_params_k4_Ppmodq_0_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_Ppmodq_1_limbs[] = {13089936UL};
static const int_t _las_pi_params_k4_Ppmodq_1 = {{(limb_t *)_las_pi_params_k4_Ppmodq_1_limbs, 1, 0}};
static const limb_t _las_pi_params_k4_Ppmodq_2_limbs[] = {7661712UL};
static const int_t _las_pi_params_k4_Ppmodq_2 = {{(limb_t *)_las_pi_params_k4_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _las_pi_params_k4_l2Bsq[] = {_las_pi_params_k4_l2Bsq0};
static const int_srcptr _las_pi_params_k4_Ppmodq[] = {_las_pi_params_k4_Ppmodq_0, _las_pi_params_k4_Ppmodq_1, _las_pi_params_k4_Ppmodq_2};
static const polyring_t _las_pi_params_k4_ring = {{_las_pi_params_k4_q, 64, 51, 6, moduli_d64, 3, _las_pi_params_k4_Pmodq, _las_pi_params_k4_Ppmodq, _las_pi_params_k4_inv2}};
static const dcompress_params_t _las_pi_params_k4_dcomp = {{ _las_pi_params_k4_q, _las_pi_params_k4_qminus1, _las_pi_params_k4_m, _las_pi_params_k4_mby2, _las_pi_params_k4_gamma, _las_pi_params_k4_gammaby2, _las_pi_params_k4_pow2D, _las_pi_params_k4_pow2Dby2, 12, 0, 30 }};
static const abdlop_params_t _las_pi_params_k4_tbox = {{ _las_pi_params_k4_ring, _las_pi_params_k4_dcomp, 369, 60, 0, 12, 16, _las_pi_params_k4_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k4_scM1, _las_pi_params_k4_stdev1sq, 2, 12, _las_pi_params_k4_scM2, _las_pi_params_k4_stdev2sq}};
static const abdlop_params_t _las_pi_params_k4_quad_eval_ = {{ _las_pi_params_k4_ring, _las_pi_params_k4_dcomp, 369, 60, 9, 3, 16, _las_pi_params_k4_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k4_scM1, _las_pi_params_k4_stdev1sq, 2, 12, _las_pi_params_k4_scM2, _las_pi_params_k4_stdev2sq}};
static const abdlop_params_t _las_pi_params_k4_quad_many_ = {{ _las_pi_params_k4_ring, _las_pi_params_k4_dcomp, 369, 60, 11, 1, 16, _las_pi_params_k4_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k4_scM1, _las_pi_params_k4_stdev1sq, 2, 12, _las_pi_params_k4_scM2, _las_pi_params_k4_stdev2sq}};
static const lnp_quad_eval_params_t _las_pi_params_k4_quad_eval = {{ _las_pi_params_k4_quad_eval_, _las_pi_params_k4_quad_many_, 4}};
static const lnp_tbox_params_t _las_pi_params_k4 = {{ _las_pi_params_k4_tbox, _las_pi_params_k4_quad_eval, 352, _las_pi_params_k4_n, 96, 1, 369, 2, 13, _las_pi_params_k4_scM3, _las_pi_params_k4_stdev3sq, 2, 19, _las_pi_params_k4_scM4, _las_pi_params_k4_stdev4sq, _las_pi_params_k4_Bz3sqr, _las_pi_params_k4_Bz4, &_las_pi_params_k4_l2Bsq[0], _las_pi_params_k4_inv4, 79936UL }};

static const unsigned int las_pi_params_k4_Ps[352] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351};
static const unsigned int las_pi_params_k4_Es0[16] = {352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367};
static const unsigned int *las_pi_params_k4_Es[1] = { las_pi_params_k4_Es0, };
static const unsigned int las_pi_params_k4_Es_nrows[1] = {16};

static const limb_t las_pi_params_k4_p_limbs[] = {8380417UL};
static const int_t las_pi_params_k4_p = {{(limb_t *)las_pi_params_k4_p_limbs, 1, 0}};
static const limb_t las_pi_params_k4_pinv_limbs[] = {115964606962967UL};
static const int_t las_pi_params_k4_pinv = {{(limb_t *)las_pi_params_k4_pinv_limbs, 1, 1}};
static const unsigned int las_pi_params_k4_s1_indices[92] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 22, 45, 68, 91};
static const lin_params_t las_pi_params_k4 = {{ _las_pi_params_k4, 256, las_pi_params_k4_p, las_pi_params_k4_pinv, 4, las_pi_params_k4_s1_indices, 92, NULL, 0,  las_pi_params_k4_Ps, 352, las_pi_params_k4_Es, las_pi_params_k4_Es_nrows, NULL, NULL }};

