// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(31,28,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(16,243,2^(35.637559))
// 
// Ring
// degree d = 64
// modulus q = 562949953422757, log(q) ~ 49.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 2075974, log(gamma) ~ 20.985357
// 
// Dimensions of secrets
// s1: m1 = 184
// m: l = 0
// s2: m2 = 59
// 
// Size of secrets
// l2(s1) <= alpha = 108.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 176)
// exact euclidean: yes (dimensions: [8], bounds: [16.0])
// approximate infinity: yes (psi: 2335.4614, dimension: 48, bound: 5888.4993)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 406323.2, log(stdev4/1.55) = 18.0
// 
// Repetition rate
// M1 = 2.7203557
// M2 = 2.5044467
// M3 = 1.01218
// M4 = 1.0360224
// total = 7.1443775
// 
// Security
// MSIS dimension: 16
// MSIS root hermite factor: 1.0043958
// MLWE dimension: 31
// MLWE root hermite factor: 1.0043649
// 
// Proof size
// ~ 47.7343750000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _las_pi_params_k2_q_limbs[] = {562949953422757UL};
static const int_t _las_pi_params_k2_q = {{(limb_t *)_las_pi_params_k2_q_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_qminus1_limbs[] = {562949953422756UL};
static const int_t _las_pi_params_k2_qminus1 = {{(limb_t *)_las_pi_params_k2_qminus1_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_m_limbs[] = {271173894UL};
static const int_t _las_pi_params_k2_m = {{(limb_t *)_las_pi_params_k2_m_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_mby2_limbs[] = {135586947UL};
static const int_t _las_pi_params_k2_mby2 = {{(limb_t *)_las_pi_params_k2_mby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_gamma_limbs[] = {2075974UL};
static const int_t _las_pi_params_k2_gamma = {{(limb_t *)_las_pi_params_k2_gamma_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_gammaby2_limbs[] = {1037987UL};
static const int_t _las_pi_params_k2_gammaby2 = {{(limb_t *)_las_pi_params_k2_gammaby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_pow2D_limbs[] = {1024UL};
static const int_t _las_pi_params_k2_pow2D = {{(limb_t *)_las_pi_params_k2_pow2D_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_pow2Dby2_limbs[] = {512UL};
static const int_t _las_pi_params_k2_pow2Dby2 = {{(limb_t *)_las_pi_params_k2_pow2Dby2_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_Bsq_limbs[] = {1300400694989378UL, 0UL};
static const int_t _las_pi_params_k2_Bsq = {{(limb_t *)_las_pi_params_k2_Bsq_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_scM1_limbs[] = {11049982582905682100UL, 13288216987762704174UL, 2UL};
static const int_t _las_pi_params_k2_scM1 = {{(limb_t *)_las_pi_params_k2_scM1_limbs, 3, 0}};
static const limb_t _las_pi_params_k2_scM2_limbs[] = {8624154020888717866UL, 9305399036312114916UL, 2UL};
static const int_t _las_pi_params_k2_scM2 = {{(limb_t *)_las_pi_params_k2_scM2_limbs, 3, 0}};
static const limb_t _las_pi_params_k2_scM3_limbs[] = {8338780990552000640UL, 224681035830479488UL, 1UL};
static const int_t _las_pi_params_k2_scM3 = {{(limb_t *)_las_pi_params_k2_scM3_limbs, 3, 0}};
static const limb_t _las_pi_params_k2_scM4_limbs[] = {9339683551355895420UL, 664496788683813239UL, 1UL};
static const int_t _las_pi_params_k2_scM4 = {{(limb_t *)_las_pi_params_k2_scM4_limbs, 3, 0}};
static const limb_t _las_pi_params_k2_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _las_pi_params_k2_stdev1sq = {{(limb_t *)_las_pi_params_k2_stdev1sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _las_pi_params_k2_stdev2sq = {{(limb_t *)_las_pi_params_k2_stdev2sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_stdev3sq_limbs[] = {161229046UL, 0UL};
static const int_t _las_pi_params_k2_stdev3sq = {{(limb_t *)_las_pi_params_k2_stdev3sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_stdev4sq_limbs[] = {165098542858UL, 0UL};
static const int_t _las_pi_params_k2_stdev4sq = {{(limb_t *)_las_pi_params_k2_stdev4sq_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_inv2_limbs[] = {281474976711378UL};
static const int_t _las_pi_params_k2_inv2 = {{(limb_t *)_las_pi_params_k2_inv2_limbs, 1, 1}};
static const limb_t _las_pi_params_k2_inv4_limbs[] = {140737488355689UL};
static const int_t _las_pi_params_k2_inv4 = {{(limb_t *)_las_pi_params_k2_inv4_limbs, 1, 1}};
static const unsigned int _las_pi_params_k2_n[1] = {8};
static const limb_t _las_pi_params_k2_Bz3sqr_limbs[] = {111012260217UL, 0UL};
static const int_t _las_pi_params_k2_Bz3sqr = {{(limb_t *)_las_pi_params_k2_Bz3sqr_limbs, 2, 0}};
static const limb_t _las_pi_params_k2_Bz4_limbs[] = {6501171UL};
static const int_t _las_pi_params_k2_Bz4 = {{(limb_t *)_las_pi_params_k2_Bz4_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_Pmodq_limbs[] = {205740889497UL};
static const int_t _las_pi_params_k2_Pmodq = {{(limb_t *)_las_pi_params_k2_Pmodq_limbs, 1, 1}};
static const limb_t _las_pi_params_k2_l2Bsq0_limbs[] = {256UL};
static const int_t _las_pi_params_k2_l2Bsq0 = {{(limb_t *)_las_pi_params_k2_l2Bsq0_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_Ppmodq_0_limbs[] = {43952337UL};
static const int_t _las_pi_params_k2_Ppmodq_0 = {{(limb_t *)_las_pi_params_k2_Ppmodq_0_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_Ppmodq_1_limbs[] = {36890961UL};
static const int_t _las_pi_params_k2_Ppmodq_1 = {{(limb_t *)_las_pi_params_k2_Ppmodq_1_limbs, 1, 0}};
static const limb_t _las_pi_params_k2_Ppmodq_2_limbs[] = {26105937UL};
static const int_t _las_pi_params_k2_Ppmodq_2 = {{(limb_t *)_las_pi_params_k2_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _las_pi_params_k2_l2Bsq[] = {_las_pi_params_k2_l2Bsq0};
static const int_srcptr _las_pi_params_k2_Ppmodq[] = {_las_pi_params_k2_Ppmodq_0, _las_pi_params_k2_Ppmodq_1, _las_pi_params_k2_Ppmodq_2};
static const polyring_t _las_pi_params_k2_ring = {{_las_pi_params_k2_q, 64, 50, 6, moduli_d64, 3, _las_pi_params_k2_Pmodq, _las_pi_params_k2_Ppmodq, _las_pi_params_k2_inv2}};
static const dcompress_params_t _las_pi_params_k2_dcomp = {{ _las_pi_params_k2_q, _las_pi_params_k2_qminus1, _las_pi_params_k2_m, _las_pi_params_k2_mby2, _las_pi_params_k2_gamma, _las_pi_params_k2_gammaby2, _las_pi_params_k2_pow2D, _las_pi_params_k2_pow2Dby2, 10, 0, 29 }};
static const abdlop_params_t _las_pi_params_k2_tbox = {{ _las_pi_params_k2_ring, _las_pi_params_k2_dcomp, 185, 59, 0, 12, 16, _las_pi_params_k2_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k2_scM1, _las_pi_params_k2_stdev1sq, 2, 12, _las_pi_params_k2_scM2, _las_pi_params_k2_stdev2sq}};
static const abdlop_params_t _las_pi_params_k2_quad_eval_ = {{ _las_pi_params_k2_ring, _las_pi_params_k2_dcomp, 185, 59, 9, 3, 16, _las_pi_params_k2_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k2_scM1, _las_pi_params_k2_stdev1sq, 2, 12, _las_pi_params_k2_scM2, _las_pi_params_k2_stdev2sq}};
static const abdlop_params_t _las_pi_params_k2_quad_many_ = {{ _las_pi_params_k2_ring, _las_pi_params_k2_dcomp, 185, 59, 11, 1, 16, _las_pi_params_k2_Bsq, 1, 8, 5, 140, 1, 17, _las_pi_params_k2_scM1, _las_pi_params_k2_stdev1sq, 2, 12, _las_pi_params_k2_scM2, _las_pi_params_k2_stdev2sq}};
static const lnp_quad_eval_params_t _las_pi_params_k2_quad_eval = {{ _las_pi_params_k2_quad_eval_, _las_pi_params_k2_quad_many_, 4}};
static const lnp_tbox_params_t _las_pi_params_k2 = {{ _las_pi_params_k2_tbox, _las_pi_params_k2_quad_eval, 176, _las_pi_params_k2_n, 48, 1, 185, 2, 13, _las_pi_params_k2_scM3, _las_pi_params_k2_stdev3sq, 2, 18, _las_pi_params_k2_scM4, _las_pi_params_k2_stdev4sq, _las_pi_params_k2_Bz3sqr, _las_pi_params_k2_Bz4, &_las_pi_params_k2_l2Bsq[0], _las_pi_params_k2_inv4, 48880UL }};

static const unsigned int las_pi_params_k2_Ps[176] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175};
static const unsigned int las_pi_params_k2_Es0[8] = {176, 177, 178, 179, 180, 181, 182, 183};
static const unsigned int *las_pi_params_k2_Es[1] = { las_pi_params_k2_Es0, };
static const unsigned int las_pi_params_k2_Es_nrows[1] = {8};

static const limb_t las_pi_params_k2_p_limbs[] = {8380417UL};
static const int_t las_pi_params_k2_p = {{(limb_t *)las_pi_params_k2_p_limbs, 1, 0}};
static const limb_t las_pi_params_k2_pinv_limbs[] = {207291638682023UL};
static const int_t las_pi_params_k2_pinv = {{(limb_t *)las_pi_params_k2_pinv_limbs, 1, 0}};
static const unsigned int las_pi_params_k2_s1_indices[46] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 22, 45};
static const lin_params_t las_pi_params_k2 = {{ _las_pi_params_k2, 256, las_pi_params_k2_p, las_pi_params_k2_pinv, 4, las_pi_params_k2_s1_indices, 46, NULL, 0,  las_pi_params_k2_Ps, 176, las_pi_params_k2_Es, las_pi_params_k2_Es_nrows, NULL, NULL }};

