#ifndef RELATION_ZK_H
#define RELATION_ZK_H

/*
 * relation_zk.{c,h} -- the proof of knowledge pi for the hard relation R_A
 * (eprint 2020/845, Section 4.1 / Fig. 1): u1 proves knowledge of a witness
 * r' with
 *
 *     A r' = t'   and   ||r'||inf <= 1        (i.e. (Y, r') in R_A)
 *
 * WITHOUT revealing r'.  Fig. 1 makes pi load-bearing for fairness: u2
 * pre-signs only after verifying pi, and the Section-4.1 M-SIS argument
 * ("s = r', hence ||s||inf <= 1, hence pre-signature adaptability") holds only
 * because pi proves the EXACT ternary bound -- an approximate/relaxed PoK (or
 * an l2-only bound) would let a malicious u1 leave u2 with an unadaptable
 * pre-signature after u1 already claimed their coin.
 *
 * Realisation: the paper suggests the Esgin-Nguyen-Seiler system; this build
 * instead reuses the vendored LaZer library (third_party/lazer, LNP22-based
 * "linear relation with norms" frontend) -- same reuse posture as vendoring
 * libsecp256k1-zkp for the classical baseline.  LaZer proves per-partition
 * BINARY coefficients or exact l2 bounds, so the ternary statement is encoded
 * by BINARY DECOMPOSITION r' = r_plus - r_minus:
 *
 *     [A | -A | 0] * (r_plus || r_minus || e) = t',
 *     r_plus, r_minus BINARY (proven),  l2(e) <= 16 (dummy, honest e = 0),
 *
 * which yields knowledge of the ternary preimage r_plus - r_minus of t'.
 * (The 23rd all-zero column exists because the LaZer codegen requires at
 * least one l2-bounded partition; it contributes nothing to the relation.)
 * Parameter set: ref/relation_zk_params.h, generated by
 * scripts/las_pi_params.py via LaZer's sage lin-codegen (knowledge error
 * <= 2^-127 under M-SIS, zero-knowledge under M-LWE, proof ~31 KiB).  pi is
 * exchanged OFF-CHAIN only (Section 4.1), so its size never touches the
 * on-chain cost story.
 *
 * Layering: pi belongs to the RELATION layer (it proves R_A membership); the
 * module is split into this protocol-facing half (ref types -> flat buffers)
 * and the LaZer bridge relation_zk_lazer.{c,h} (flat buffers -> LaZer types),
 * because ref headers and lazer.h cannot share a translation unit.
 *
 * The generated parameter set is FIXED to the D3 engineering set (n=6, ell=5,
 * d=256, q=8380417); other parameter sets need their own codegen run.
 */

#include <stddef.h>
#include <stdint.h>
#include "setup.h"            /* construction parameters + public_params */
#include "las_types.h"        /* statement, witness */
#include "relation_zk_lazer.h" /* PI_PROOF_MAX_BYTES + bridge dimensions */

/* pi <- P((t'; r'), {exists r' : A r' = t' and ||r'||inf <= 1})  (Fig. 1).
 * Rejects (returns -1, no proof) if the witness is not ternary: only an
 * HONEST Gen witness can be proven -- an Ext-extracted witness from the
 * extended relation R'_A (the knowledge gap) is not a valid pi witness.
 * On success returns 0 and writes the proof and its exact length.
 * NOT thread-safe (static statement staging buffers). */
int relation_prove(uint8_t proof[PI_PROOF_MAX_BYTES], size_t *prooflen,
                   const statement *Y, const witness *r_prime,
                   const public_params *pp);

/* Verify pi against (pp, Y).  0 = accept, -1 = reject.
 * NOT thread-safe (static statement staging buffers). */
int relation_proof_verify(const uint8_t *proof, size_t prooflen,
                          const statement *Y, const public_params *pp);

#endif
