#!/usr/bin/env python3
"""Emit report macros for the real-client Bitcoin runs (Stages 2 and 3).

Every value is PARSED from a run's own evidence — the client's `getrawtransaction` output,
its `testmempoolaccept` verdict, the recorded pins — and never typed here. That is the same
rule `gen_bitcoin_tx_data.py` follows, and the reason the report can quote these figures at
all: a number typed into a script is a number that silently stops matching the run.

Reads   evidence/btc_regtest/latest/   (stock Core: carriage)
        evidence/btc_las_node/latest/  (patched Core: verification, one spend)
        evidence/btc_twoleg/latest/    (patched Core: a whole two-leg swap)
Writes  report/latex/generated/btcnodemacros.tex

THE THREE RUNS ARE KEPT APART, and their macros are named apart, because they support
different claims: carriage verifies nothing, the single spend verifies one signature, and
only the two-leg run settles a swap. Mixing their control counts or sizes into one figure
would let a sentence about one run quote a number from another.

Usage: gen_btc_regtest_data.py [--regtest DIR] [--lasnode DIR] [--twoleg DIR] [--out FILE]
"""
import argparse
import json
import pathlib
import sys

HEADER = (
    "% GENERATED by scripts/gen_btc_regtest_data.py -- DO NOT EDIT.\n"
    "% Parsed from each run's evidence under evidence/btc_{regtest,las_node,twoleg}/latest.\n"
    "% Provenance differs by macro and is not uniform: transaction sizes come from the\n"
    "% clients' own getrawtransaction records, while control counts, the witness-recovery\n"
    "% report and the pass verdict are artefacts of this project's runner and helpers,\n"
    "% recording the clients' answers. Never hand-type a figure here.\n"
    "% btcMeas* = stock carriage; btcLas* = the single verified spend; btcSwap* = the\n"
    "% two-leg swap. Three separate runs: never mix their numbers.\n"
    "% Write-up: docs/03-results/TWO_LEG_REAL_CLIENT_EXPERIMENT.md\n"
)


def die(msg):
    sys.exit("gen_btc_regtest_data: " + msg)


def load(path):
    if not path.exists():
        die(f"missing {path} — run the corresponding runner first")
    return json.loads(path.read_text())


def env_value(envfile, key):
    """One `key=value` line from a run's environment.txt."""
    if not envfile.exists():
        die(f"missing {envfile}")
    for line in envfile.read_text().splitlines():
        if line.startswith(key + "="):
            return line.split("=", 1)[1].strip()
    die(f"{envfile} has no '{key}=' line")


def policy_verdict(path):
    """ACCEPTED, or the client's own reject reason — never paraphrased."""
    r = load(path)[0]
    return "accepted" if r["allowed"] else r.get("reject-reason", "?")


def main():
    repo = pathlib.Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--regtest", type=pathlib.Path,
                    default=repo / "evidence/btc_regtest/latest")
    ap.add_argument("--lasnode", type=pathlib.Path,
                    default=repo / "evidence/btc_las_node/latest")
    ap.add_argument("--twoleg", type=pathlib.Path,
                    default=repo / "evidence/btc_twoleg/latest")
    ap.add_argument("--out", type=pathlib.Path,
                    default=repo / "report/latex/generated/btcnodemacros.tex")
    args = ap.parse_args()

    out = [HEADER, ""]

    def emit(name, value):
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    # --- Stage 2: stock Core, carriage only -------------------------------------------
    env = args.regtest / "environment.txt"
    emit("btcNodeTag", env_value(env, "btc_tag"))
    emit("btcNodeCommit", env_value(env, "btc_src_head")[:12])
    out.append("")

    for label, macro in (("A1", "Wpkh"), ("A2", "Tr"), ("A3", "Carriage")):
        mined = load(args.regtest / f"{label}_mined.json")
        emit(f"btcMeas{macro}Vsize", f"{mined['vsize']:,}".replace(",", "{,}"))
        emit(f"btcMeas{macro}Weight", f"{mined['weight']:,}".replace(",", "{,}"))
        verdict = policy_verdict(args.regtest / f"{label}_testmempoolaccept_default.json")
        emit(f"btcMeas{macro}Policy", verdict.replace("_", "\\_"))
    out.append("")

    # The carriage transaction's witness shape, so the appendix can say what those bytes
    # are without the reader having to take the chunk count on trust.
    build = load(args.regtest / "A3_build.json")
    emit("btcChunkWidth", build["chunk_width"])
    emit("btcSigChunks", build["sig_chunks"])
    emit("btcPkChunks", build["pk_chunks"])
    emit("btcCarriageItems", build["witness_items"])
    out.append("")

    # --- Stage 3: patched Core, verification ------------------------------------------
    lenv = args.lasnode / "environment.txt"
    emit("btcLasPatchSha", env_value(lenv, "patch_sha256")[:12])
    # The opcode number is PARSED from what the run recorded, not written here. Hardcoding
    # it would put a value in the report that no longer tracks the patch, while this file's
    # own docstring promised the opposite — a provenance claim the generator would break.
    opcode_line = env_value(lenv, "opcode")
    opcode = next((tok.strip("(),") for tok in opcode_line.split()
                   if tok.strip("(),").startswith("0x")), None)
    if opcode is None:
        die(f"the run's environment.txt records no opcode number: {opcode_line!r}")
    emit("btcLasOpcode", opcode)
    mined = load(args.lasnode / "mined.json")
    emit("btcLasVsize", f"{mined['vsize']:,}".replace(",", "{,}"))
    emit("btcLasWeight", f"{mined['weight']:,}".replace(",", "{,}"))
    spend = load(args.lasnode / "valid_spend.json")
    emit("btcLasItems", spend["witness_items"])

    # How many negative controls actually ran, counted from the evidence rather than
    # asserted: a control that stopped running would otherwise keep being reported.
    controls = (args.lasnode / "controls.txt").read_text().splitlines()
    negatives = [c for c in controls if c.strip() and not c.startswith("valid")]
    if not negatives:
        die("controls.txt lists no negative controls")
    for c in negatives:
        if "patched: REJECTED" not in c or "stock: ACCEPTED" not in c:
            die(f"a recorded control is not REJECTED/ACCEPTED: {c.strip()!r}")
    emit("btcLasControls", len(negatives))
    out.append("")

    # --- Stage 4: patched Core, a WHOLE two-leg swap ------------------------------------
    # The run's own verdict is checked first. Its runner already refuses to move `latest`
    # on a failure, but a macro file is the one artefact that outlives the run, so the
    # success line is confirmed here rather than assumed from the directory existing.
    verdict = (args.twoleg / "verdict.txt").read_text()
    if "RESULT: a two-leg atomic swap settled" not in verdict:
        die(f"{args.twoleg}/verdict.txt does not record a passing two-leg swap")
    if "identical to the Adapt output          : YES" not in verdict:
        die("the two-leg run did not confirm the chain-recovered signature against the "
            "Adapt output — its provenance claim is unmet, so no macro may quote it")

    # Every per-leg figure is read from the MINED transaction, not from the assembler's
    # leg*_spend.json: the latter is what this project intended to broadcast, and what the
    # report wants is what the chain actually carried.
    legs = {}
    for leg in ("A", "B"):
        mined = load(args.twoleg / f"leg{leg}_mined.json")
        # BIP141 defines weight = 3*base + total, so the base (non-witness) size follows
        # EXACTLY from two integers the client itself reported -- it is arithmetic on
        # measured values, not a second model of the serialization. Everything the witness
        # discount applies to is then total - base. This is what lets the deck state a
        # per-field split without falling back on the projected btcThree* figures.
        base = (mined["weight"] - mined["size"]) // 3
        if 3 * base + mined["size"] != mined["weight"]:
            die(f"leg {leg}: weight {mined['weight']} is not 3*base + size for size "
                f"{mined['size']}; the client's own fields disagree, so no macro may "
                "quote a base/witness split from them")
        # ⚠ size - base is NOT the witness: BIP141's total_size also carries BIP144's
        # marker and flag, which are fixed at one byte each for every segwit transaction.
        # Subtracting those 2 is exact, not a model, and without it the witness figure is
        # 2 B too large -- enough to make a stated "witness = N B" claim simply wrong.
        witness = mined["size"] - base - 2
        legs[leg] = (mined["vsize"], mined["weight"],
                     len(mined["vin"][0]["txinwitness"]),
                     base, witness)
    # These macros are quoted as "each leg", so EVERY one of them is gated on the two legs
    # agreeing — size, weight and witness count alike. They need not agree: a beneficiary
    # paid to a different output type changes the size, and a different signature length
    # would change the chunk count. Rather than let "each leg" quietly become false, this
    # stops and tells the author to name the legs separately first.
    if legs["A"] != legs["B"]:
        die(f"the two legs differ (vsize, weight, witness items): {legs['A']} vs "
            f"{legs['B']}. The report's per-leg phrasing must name them separately "
            "before these macros can be emitted.")
    emit("btcSwapLegVsize", f"{legs['A'][0]:,}".replace(",", "{,}"))
    emit("btcSwapLegWeight", f"{legs['A'][1]:,}".replace(",", "{,}"))
    emit("btcSwapItems", legs["A"][2])
    emit("btcSwapLegBase", f"{legs['A'][3]:,}".replace(",", "{,}"))
    emit("btcSwapLegWitness", f"{legs['A'][4]:,}".replace(",", "{,}"))

    # The signature recovered FROM the mined witness, and where its boundary was found.
    # Reported as measured bytes so the appendix never restates SIGNATURE_BYTES from memory.
    rec = load(args.twoleg / "recovered_sigB.json")
    emit("btcSwapRecoveredBytes", f"{rec['sig_bytes']:,}".replace(",", "{,}"))

    # Counted, and each one checked, exactly as for the single-spend run above. Note the
    # label here is `leg{A,B}_valid`, not `valid`, so the filter differs by necessity.
    tl_controls = (args.twoleg / "controls.txt").read_text().splitlines()
    tl_neg = [c for c in tl_controls if c.strip() and "_valid" not in c.split()[0]]
    if not tl_neg:
        die("the two-leg controls.txt lists no negative controls")
    for c in tl_neg:
        if "patched: REJECTED" not in c or "stock: ACCEPTED" not in c:
            die(f"a recorded two-leg control is not REJECTED/ACCEPTED: {c.strip()!r}")
    emit("btcSwapControls", len(tl_neg))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(negatives)} single-spend + {len(tl_neg)} two-leg "
          "negative controls verified)")


if __name__ == "__main__":
    main()
