#!/usr/bin/env python3
"""Emit report macros for the real-client Bitcoin runs (Stages 2 and 3).

Every value is PARSED from a run's own evidence — the client's `getrawtransaction` output,
its `testmempoolaccept` verdict, the recorded pins — and never typed here. That is the same
rule `gen_bitcoin_tx_data.py` follows, and the reason the report can quote these figures at
all: a number typed into a script is a number that silently stops matching the run.

Reads   evidence/btc_regtest/latest/   (stock Core: carriage)
        evidence/btc_las_node/latest/  (patched Core: verification)
Writes  report/latex/generated/btcnodemacros.tex

Usage: gen_btc_regtest_data.py [--regtest DIR] [--lasnode DIR] [--out FILE]
"""
import argparse
import json
import pathlib
import sys

HEADER = (
    "% GENERATED by scripts/gen_btc_regtest_data.py -- DO NOT EDIT.\n"
    "% Values parsed from the clients' own output in evidence/btc_regtest/latest and\n"
    "% evidence/btc_las_node/latest. Never hand-type a figure here.\n"
    "% Write-up: docs/03-results/TWO_LEG_REAL_CLIENT_EXPERIMENT.md\n"
)


def die(msg):
    sys.exit("gen_btc_regtest_data: " + msg)


def load(path):
    if not path.exists():
        die(f"missing {path} — run the corresponding runner first")
    return json.loads(path.read_text())


def env_value(envfile, key):
    """One `key=value` line from a run's environment.txt."""
    if not envfile.exists():
        die(f"missing {envfile}")
    for line in envfile.read_text().splitlines():
        if line.startswith(key + "="):
            return line.split("=", 1)[1].strip()
    die(f"{envfile} has no '{key}=' line")


def policy_verdict(path):
    """ACCEPTED, or the client's own reject reason — never paraphrased."""
    r = load(path)[0]
    return "accepted" if r["allowed"] else r.get("reject-reason", "?")


def main():
    repo = pathlib.Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser()
    ap.add_argument("--regtest", type=pathlib.Path,
                    default=repo / "evidence/btc_regtest/latest")
    ap.add_argument("--lasnode", type=pathlib.Path,
                    default=repo / "evidence/btc_las_node/latest")
    ap.add_argument("--out", type=pathlib.Path,
                    default=repo / "report/latex/generated/btcnodemacros.tex")
    args = ap.parse_args()

    out = [HEADER, ""]

    def emit(name, value):
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    # --- Stage 2: stock Core, carriage only -------------------------------------------
    env = args.regtest / "environment.txt"
    emit("btcNodeTag", env_value(env, "btc_tag"))
    emit("btcNodeCommit", env_value(env, "btc_src_head")[:12])
    out.append("")

    for label, macro in (("A1", "Wpkh"), ("A2", "Tr"), ("A3", "Carriage")):
        mined = load(args.regtest / f"{label}_mined.json")
        emit(f"btcMeas{macro}Vsize", f"{mined['vsize']:,}".replace(",", "{,}"))
        emit(f"btcMeas{macro}Weight", f"{mined['weight']:,}".replace(",", "{,}"))
        verdict = policy_verdict(args.regtest / f"{label}_testmempoolaccept_default.json")
        emit(f"btcMeas{macro}Policy", verdict.replace("_", "\\_"))
    out.append("")

    # The carriage transaction's witness shape, so the appendix can say what those bytes
    # are without the reader having to take the chunk count on trust.
    build = load(args.regtest / "A3_build.json")
    emit("btcChunkWidth", build["chunk_width"])
    emit("btcSigChunks", build["sig_chunks"])
    emit("btcPkChunks", build["pk_chunks"])
    emit("btcCarriageItems", build["witness_items"])
    out.append("")

    # --- Stage 3: patched Core, verification ------------------------------------------
    lenv = args.lasnode / "environment.txt"
    emit("btcLasPatchSha", env_value(lenv, "patch_sha256")[:12])
    # The opcode number is PARSED from what the run recorded, not written here. Hardcoding
    # it would put a value in the report that no longer tracks the patch, while this file's
    # own docstring promised the opposite — a provenance claim the generator would break.
    opcode_line = env_value(lenv, "opcode")
    opcode = next((tok.strip("(),") for tok in opcode_line.split()
                   if tok.strip("(),").startswith("0x")), None)
    if opcode is None:
        die(f"the run's environment.txt records no opcode number: {opcode_line!r}")
    emit("btcLasOpcode", opcode)
    mined = load(args.lasnode / "mined.json")
    emit("btcLasVsize", f"{mined['vsize']:,}".replace(",", "{,}"))
    emit("btcLasWeight", f"{mined['weight']:,}".replace(",", "{,}"))
    spend = load(args.lasnode / "valid_spend.json")
    emit("btcLasItems", spend["witness_items"])

    # How many negative controls actually ran, counted from the evidence rather than
    # asserted: a control that stopped running would otherwise keep being reported.
    controls = (args.lasnode / "controls.txt").read_text().splitlines()
    negatives = [c for c in controls if c.strip() and not c.startswith("valid")]
    if not negatives:
        die("controls.txt lists no negative controls")
    for c in negatives:
        if "patched: REJECTED" not in c or "stock: ACCEPTED" not in c:
            die(f"a recorded control is not REJECTED/ACCEPTED: {c.strip()!r}")
    emit("btcLasControls", len(negatives))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n")
    print(f"wrote {args.out} ({len(negatives)} negative controls verified)")


if __name__ == "__main__":
    main()
