#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
STAMP="$(date +%Y%m%d_%H%M%S)"
OUT="$ROOT/evidence/final-runs/$STAMP"

mkdir -p "$OUT"

echo "Saving final evidence to: $OUT"

{
  echo "# Final Evidence Run"
  echo
  echo "Date: $(date)"
  echo "Branch: $(git branch --show-current)"
  echo "Commit: $(git rev-parse HEAD)"
  echo
  echo "## Git status"
  git status -sb
  echo
  echo "## System"
  uname -a || true
  echo
  echo "## Compiler"
  cc --version | head -n 1 || true
  echo
  echo "## Notes"
  echo "- Generated by scripts/run_final_evidence.sh"
  echo "- Do not overwrite this directory."
  echo "- Use this folder as raw evidence for report appendix."
} > "$OUT/MANIFEST.md"

cd "$ROOT/ref"

{
  make test/test_las3
  ./test/test_las3
} | tee "$OUT/functional_tests.log"

{
  make test/test_contract3
  ./test/test_contract3
} | tee "$OUT/contract.log"

{
  make test/test_serde3
  ./test/test_serde3
} | tee "$OUT/serialization_tests.log"

{
  make test/test_kat3
  ./test/test_kat3
} | tee "$OUT/kat.log"

{
  make test/test_swap3
  ./test/test_swap3
} | tee "$OUT/atomic_swap.log"

{
  make test/test_pcn3
  ./test/test_pcn3
} | tee "$OUT/pcn.log"

{
  make test/bench_levels_paper
  ./test/bench_levels_paper
} | tee "$OUT/fair_paper.log"

{
  make test/bench_levels2
  ./test/bench_levels2
} | tee "$OUT/fair_l2.log"

{
  make test/bench_levels3
  ./test/bench_levels3
} | tee "$OUT/fair_l3.log"

{
  make test/bench_levels5
  ./test/bench_levels5
} | tee "$OUT/fair_l5.log"

{
  make test/bench_las3
  ./test/bench_las3
} | tee "$OUT/rejection_rate.log"

{
  make test/bench_app3
  ./test/bench_app3
} | tee "$OUT/application_benchmark.log"

echo
echo "Final evidence saved to:"
echo "$OUT"
echo
echo "Next:"
echo "1. Check logs for PASS/FAIL."
echo "2. Copy key numbers into docs/STATUS.md only if this is the accepted final run."
echo "3. Cite this folder in the report appendix."
