#!/usr/bin/env python3
"""Refresh the AUTO-CONTEXT block inside CLAUDE.md from the working tree.

CLAUDE.md is the file every Claude Code session reads first.  Its hand-written
sections (focus, naming convention, scope rules, guardrails) change rarely and
are edited by a human.  Its *live* facts -- branch, HEAD, KAT digest, wire
sizes, evidence run ids, report word count, last checkpoint -- go stale within
days, and a stale CLAUDE.md is worse than none: it teaches the next session a
number that is no longer true.

This script regenerates only the region between

    <!-- BEGIN AUTO-CONTEXT ... -->   and   <!-- END AUTO-CONTEXT -->

so the two halves cannot drift into each other.

Discipline it inherits from the project guardrails:

  * it NEVER builds, runs a test, or runs a benchmark -- it only reads files
    and asks git for metadata;
  * it NEVER estimates: every figure printed is parsed out of a real file, and
    anything it cannot parse is printed as ``(not found)`` rather than guessed;
  * it is idempotent -- if the regenerated block is byte-identical to the one
    already in CLAUDE.md, the file is left untouched.

Usage::

    python3 scripts/update_claude_context.py              # rewrite the block
    python3 scripts/update_claude_context.py --print      # block to stdout only
    python3 scripts/update_claude_context.py --check      # exit 1 if stale
    python3 scripts/update_claude_context.py --hook session-start
    python3 scripts/update_claude_context.py --hook stop

The two ``--hook`` forms are what ``.claude/settings.json`` invokes; they
rewrite the file and emit the JSON envelope Claude Code expects (session-start
also injects the fresh block straight into the session context, so the block is
current even if the hook runs after CLAUDE.md was read).

Exit status is 0 in every mode except ``--check``, so a hook can never break a
session.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLAUDE_MD = ROOT / "CLAUDE.md"

BEGIN = "<!-- BEGIN AUTO-CONTEXT"
END = "<!-- END AUTO-CONTEXT -->"
BEGIN_LINE = (
    "<!-- BEGIN AUTO-CONTEXT — regenerated by scripts/update_claude_context.py. "
    "DO NOT EDIT BY HAND: edits here are overwritten on the next session start. -->"
)

MISSING = "(not found)"


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def git(*args: str) -> str:
    """Run a read-only git command; return '' on any failure."""
    try:
        out = subprocess.run(
            ["git", "-C", str(ROOT), *args],
            capture_output=True,
            text=True,
            timeout=15,
        )
        return out.stdout.strip() if out.returncode == 0 else ""
    except Exception:
        return ""


def read(path: Path, limit: int | None = None) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""
    return text[:limit] if limit else text


def hexbytes(text: str, pattern: str) -> str:
    """Pull a 0x.., 0x.. byte list out of `text` and return it as a hex string."""
    m = re.search(pattern, text, re.S)
    if not m:
        return ""
    body = m.group(1)
    return "".join(f"{int(b, 16):02x}" for b in re.findall(r"0x([0-9a-fA-F]{2})", body))


def link_target(path: Path) -> str:
    try:
        if path.is_symlink():
            return os.readlink(path)
        if path.exists():
            return path.name
    except Exception:
        pass
    return ""


def mtime(path: Path) -> _dt.datetime | None:
    try:
        return _dt.datetime.fromtimestamp(path.stat().st_mtime)
    except Exception:
        return None


def stamp(path: Path) -> str:
    t = mtime(path)
    return t.strftime("%Y-%m-%d") if t else "?"


def newest_mtime(*globs: str) -> tuple[_dt.datetime | None, Path | None]:
    best_t: _dt.datetime | None = None
    best_p: Path | None = None
    for pattern in globs:
        for p in ROOT.glob(pattern):
            if "target" in p.parts or "third_party" in p.parts:
                continue
            t = mtime(p)
            if t and (best_t is None or t > best_t):
                best_t, best_p = t, p
    return best_t, best_p


# --------------------------------------------------------------------------
# collectors -- each returns markdown lines, never raises
# --------------------------------------------------------------------------
def section_repo() -> list[str]:
    branch = git("rev-parse", "--abbrev-ref", "HEAD") or MISSING
    head = git("log", "-1", "--format=%h · %ad · %s", "--date=short") or MISSING
    porcelain = git("status", "--porcelain")
    modified = sum(1 for ln in porcelain.splitlines() if ln[:2] != "??")
    untracked = sum(1 for ln in porcelain.splitlines() if ln.startswith("??"))
    upstream = git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}")
    if upstream:
        counts = git("rev-list", "--left-right", "--count", f"{upstream}...HEAD")
        behind, ahead = (counts.split() + ["?", "?"])[:2]
        sync = f"vs `{upstream}`: {ahead} ahead, {behind} behind"
    else:
        sync = "no upstream tracking branch"

    lines = [
        "### Repository right now",
        "",
        f"- Branch **`{branch}`** · HEAD {head}",
        f"- Working tree: {modified} modified tracked file(s), {untracked} untracked path(s) · {sync}",
    ]
    recent = git("log", "-5", "--format=%h %ad %s", "--date=short")
    if recent:
        lines.append("- Recent commits:")
        lines += [f"  - `{ln}`" for ln in recent.splitlines()]
    return lines


def section_crypto() -> list[str]:
    """Wire sizes + KAT digest: the two things that silently invalidate the report."""
    serialize = read(ROOT / "ref" / "serialize.h")
    lines = ["### Target parameter set — anchors parsed from source", ""]

    m = re.search(
        r"_Static_assert\((.*?)\"wire-size anchor: D3-aligned target set\"", serialize, re.S
    )
    if m:
        body = " ".join(m.group(1).split())
        vals = dict(re.findall(r"(\w+)\s*==\s*(\d+)", body))
        lines.append(
            "- Simplified Dilithium-III / ML-DSA-65-aligned (n=6, ℓ=5, κ=49): "
            f"`c_tilde` {vals.get('LAS_CTILDEBYTES', '?')} B · "
            f"public key {vals.get('PUBLIC_KEY_BYTES', '?')} B · "
            f"secret key {vals.get('SECRET_KEY_BYTES', '?')} B · "
            f"signature = pre-signature {vals.get('SIGNATURE_BYTES', '?')} B "
            "(`ref/serialize.h` static assert)"
        )
    else:
        lines.append(f"- Wire-size anchors {MISSING} in `ref/serialize.h`")

    other = re.findall(
        r"_Static_assert\((.*?)\"wire-size anchor: ([^\"]+)\"", serialize, re.S
    )
    sweep = []
    for body, label in other:
        if "D3-aligned" in label:
            continue
        vals = dict(re.findall(r"(\w+)\s*==\s*(\d+)", " ".join(body.split())))
        sweep.append(f"{label.replace(' set', '')} {vals.get('SIGNATURE_BYTES', '?')} B")
    if sweep:
        lines.append("- Other sets (signature bytes): " + " · ".join(sweep))

    c_kat = hexbytes(
        read(ROOT / "ref" / "test" / "test_kat.c"),
        r"static const uint8_t EXPECTED\[32\]\s*=\s*\{(.*?)\}",
    )
    rs_kat = hexbytes(
        read(ROOT / "rust" / "fips204-las" / "tests" / "las_kat.rs"),
        r"const EXPECTED:\s*\[u8;\s*32\]\s*=\s*\[(.*?)\]",
    )
    if c_kat and rs_kat:
        agree = "C and Rust agree ✅" if c_kat == rs_kat else "⚠ **C and Rust DISAGREE**"
        lines.append(f"- Pinned KAT digest `{c_kat[:8]}…{c_kat[-4:]}` — {agree}")
        lines.append(f"  - full: `{c_kat}`")
        if c_kat != rs_kat:
            lines.append(f"  - Rust: `{rs_kat}`")
    else:
        lines.append(f"- Pinned KAT digest {MISSING} (C `{bool(c_kat)}`, Rust `{bool(rs_kat)}`)")
    return lines


def section_evidence() -> list[str]:
    lines = ["### Latest measured evidence (pointers only — never retype a number)", ""]
    for label, path in [
        ("Stage-1 benchmark suite", ROOT / "evidence" / "latest"),
        ("Stage-2 UTXO swap", ROOT / "evidence" / "stage2" / "latest"),
        ("On-chain gas (EVM)", ROOT / "evidence" / "onchain" / "latest"),
        ("Criterion micro-bench", ROOT / "evidence" / "criterion" / "latest"),
        ("las-stark", ROOT / "evidence" / "stark" / "latest"),
    ]:
        target = link_target(path)
        rel = path.relative_to(ROOT)
        if target:
            lines.append(f"- {label}: `{rel}` → `{target}` (dir mtime {stamp(path.resolve())})")
        else:
            lines.append(f"- {label}: {MISSING} at `{rel}`")

    wc = read(ROOT / "report" / "latex" / "word.count").strip()
    if wc:
        lines.append(
            f"- Report word count: **{wc}** "
            f"(`report/latex/word.count`, rubric bound 7,000–9,000; `make -C report/latex wordcount`)"
        )
    else:
        lines.append(f"- Report word count: {MISSING}")
    return lines


def section_checkpoint() -> list[str]:
    lines = ["### Where the last session stopped", ""]
    prog = ROOT / "PROGRESS.md"
    text = read(prog)
    if not text:
        lines.append(f"- `PROGRESS.md` {MISSING}")
        return lines

    heads = [ln for ln in text.splitlines() if ln.startswith("## ")]
    if heads:
        lines.append(f"- Last checkpoint in `PROGRESS.md`: {heads[-1].lstrip('# ').strip()}")
    tail = text.rsplit("Next action", 1)
    if len(tail) == 2:
        nxt = [ln.strip() for ln in tail[1].splitlines() if ln.strip()][:6]
        if nxt:
            lines.append("- Next action recorded there:")
            lines += [f"  - {ln.lstrip('-: ').strip()}" for ln in nxt if ln not in (":", "-")]
    ctx = read(ROOT / "CONTEXT.md", 400).splitlines()
    if ctx:
        lines.append(f"- `CONTEXT.md` (long-form handoff): {ctx[0].lstrip('# ').strip()}")
    return lines


def section_meetings() -> list[str]:
    lines = ["### Supervisor meetings on record", ""]
    nums = sorted(
        int(m.group(1))
        for p in ROOT.glob("meeting*_cleaned_transcript*.md")
        if (m := re.match(r"meeting(\d+)", p.name))
    )
    consolidated = read(ROOT / "las-context-consolidated.md")
    # The file's own title declares its coverage, e.g. "(Meetings 1 + 2 + 3 + 4 + 5 + 7)".
    title = re.search(r"Consolidated Context \(Meetings ([\d\s+]+)\)", consolidated)
    covered = sorted(int(n) for n in re.findall(r"\d+", title.group(1))) if title else []
    covered = sorted(
        set(covered) | {int(n) for n in re.findall(r"§\d+\. Meeting-(\d+) directives", consolidated)}
    )
    if nums:
        lines.append(
            "- Cleaned transcripts present: "
            + ", ".join(str(n) for n in nums)
            + " (`meetingN_cleaned_transcript.md`)"
        )
    if covered:
        lines.append(
            "- Merged into `las-context-consolidated.md` (the objectives spec): meetings "
            + ", ".join(str(n) for n in covered)
        )
    gap = [n for n in nums if n not in covered]
    if gap:
        noun = "meetings" if len(gap) > 1 else "meeting"
        # The Meeting-6 aside only applies while 6 is actually the gap; naming it
        # unconditionally would misattribute a future unmerged meeting.
        aside = (
            " (meeting 6's per-item delivery status stays in "
            "`docs/04-evaluation/SUPERVISOR_DELIVERABLES_GAP.md`)"
            if 6 in gap
            else ""
        )
        lines.append(
            f"- ⚠ **NOT in that file**: {noun} "
            + ", ".join(str(n) for n in gap)
            + " — read the transcript/summary directly before planning work it touches"
            + aside
        )
    return lines


def section_flags() -> list[str]:
    """Cheap staleness tripwires. Each states the fact, not a verdict."""
    lines = ["### Freshness tripwires", ""]
    ev = (ROOT / "evidence" / "latest").resolve()
    ev_t = mtime(ev)
    src_t, src_p = newest_mtime(
        "ref/*.c", "ref/*.h", "rust/fips204-las/src/*.rs", "rust/las-swap/src/*.rs"
    )
    if ev_t and src_t:
        if src_t > ev_t:
            lines.append(
                f"- ⚠ Source newer than Stage-1 evidence: `{src_p.relative_to(ROOT)}` "
                f"({src_t:%Y-%m-%d %H:%M}) > `evidence/latest` ({ev_t:%Y-%m-%d %H:%M}). "
                "Numbers in the report may predate the code — re-run the suite before quoting them."
            )
        else:
            lines.append(
                f"- Stage-1 evidence ({ev_t:%Y-%m-%d}) is newer than the newest scheme source "
                f"({src_t:%Y-%m-%d}) — measurements match the code."
            )
    claude_t = mtime(CLAUDE_MD)
    if claude_t:
        lines.append(f"- `CLAUDE.md` hand-written sections last touched {claude_t:%Y-%m-%d}.")
    return lines


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------
def build_block() -> str:
    now = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
    parts: list[str] = [
        BEGIN_LINE,
        "",
        "## 🔄 Live project state (auto-generated)",
        "",
        f"*Regenerated {now} by `scripts/update_claude_context.py`, which only reads files and "
        "git metadata — it never builds, tests, or benchmarks, and never estimates a number. "
        "Anything it could not parse says (not found).*",
        "",
    ]
    for collector in (
        section_repo,
        section_crypto,
        section_evidence,
        section_checkpoint,
        section_meetings,
        section_flags,
    ):
        try:
            parts += collector() + [""]
        except Exception as exc:  # a broken collector must not break the session
            parts += [f"- (collector `{collector.__name__}` failed: {exc})", ""]
    parts.append(END)
    return "\n".join(parts).rstrip() + "\n"


def splice(doc: str, block: str) -> str | None:
    """Replace the marked region. Returns None if the markers are absent."""
    start = doc.find(BEGIN)
    end = doc.find(END)
    if start == -1 or end == -1 or end < start:
        return None
    return doc[:start] + block.rstrip("\n") + doc[end + len(END) :]


def strip_volatile(text: str) -> str:
    """Drop the 'Regenerated <clock>' line so a bare clock tick is not a change.

    The Stop hook fires on every turn; without this the timestamp alone would
    dirty CLAUDE.md continuously and bury real state changes in git noise.
    """
    return "\n".join(ln for ln in text.splitlines() if not ln.startswith("*Regenerated "))


def refresh() -> tuple[bool, str]:
    """Rewrite CLAUDE.md's block if its *content* changed. Returns (changed, block)."""
    block = build_block()
    doc = read(CLAUDE_MD)
    if not doc:
        return False, block
    new = splice(doc, block)
    if new is None or strip_volatile(new) == strip_volatile(doc):
        return False, block
    CLAUDE_MD.write_text(new, encoding="utf-8")
    return True, block


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--print", action="store_true", help="print the block, do not write")
    ap.add_argument("--check", action="store_true", help="exit 1 if CLAUDE.md is stale")
    ap.add_argument("--hook", choices=["session-start", "stop"], help="hook mode (emits JSON)")
    args = ap.parse_args()

    if args.print:
        sys.stdout.write(build_block())
        return 0

    if args.check:
        block = build_block()
        doc = read(CLAUDE_MD)
        new = splice(doc, block) if doc else None
        if new is None:
            print("CLAUDE.md: AUTO-CONTEXT markers not found", file=sys.stderr)
            return 1
        if strip_volatile(new) != strip_volatile(doc):
            print("CLAUDE.md: AUTO-CONTEXT block is stale", file=sys.stderr)
            return 1
        print("CLAUDE.md: AUTO-CONTEXT block is current")
        return 0

    changed, block = refresh()

    if args.hook == "session-start":
        print(
            json.dumps(
                {
                    "hookSpecificOutput": {
                        "hookEventName": "SessionStart",
                        "additionalContext": (
                            "Live repository state, freshly regenerated into CLAUDE.md. "
                            "These values override any older figures elsewhere in context:\n\n"
                            + block
                        ),
                    },
                    "suppressOutput": True,
                }
            )
        )
    elif args.hook == "stop":
        print(json.dumps({"suppressOutput": True}))
    else:
        print("CLAUDE.md AUTO-CONTEXT " + ("updated" if changed else "already current"))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never break a session over a context refresh
        print(f"update_claude_context: {exc}", file=sys.stderr)
        sys.exit(0)
